services:
  db:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_db
    ports:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
        interval: 10s
        timeout: 5s
        retries: 5

  backend:
    image: hospital_backend:v1.0.0
    build: .
    container_name: backend_container
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: hospital_db
    ports:
      - "8999:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network


volumes:
  db_data:

networks:
  app_network: